apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: eshtry-mny
data:
  NODE_ENV: {{ .Values.nodeEnv | default "production" | quote }}
  MONGO_CLUSTER: {{ .Values.secrets.mongoCluster | quote }}
  MONGO_DBNAME: {{ .Values.secrets.mongoDbname | quote }}
  PRODUCT_SERVICE_URL: "http://product-service:9000"
