apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: eshtry-mny
type: Opaque
stringData:
  MONGO_USERNAME: {{ .Values.secrets.mongoUsername | quote }}
  MONGO_PASSWORD: {{ .Values.secrets.mongoPassword | quote }}
  ACCESS_TOKEN: {{ .Values.secrets.accessToken | quote }}
