apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: eshtry-mny
data:
  NODE_ENV: "production"
  MONGO_CLUSTER: "cluster0.inpzonw.mongodb.net"
  MONGO_DBNAME: "eshtry_mny"
  PRODUCT_SERVICE_URL: "http://product-service:9000"
